version: '2'

services:
  dynamo:
    restart: unless-stopped
    image: amazon/dynamodb-local:1.16.0
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8042:8000"
    env_file:
      - ../.env

  django:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "80:4000"
    volumes:
      - ../:/app/
    depends_on:
      - dynamo
    links:
      - "dynamo:db"
    env_file:
      - ../.env
