# Generated by Django 3.2.2 on 2021-05-11 14:19

from django.db import migrations
from ..models import Booking
from dynamodb import Connector


def create_dynamo_models():
    Connector(Booking).create_table()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dynamo_models, migrations.RunPython.noop),
    ]
